---
Standards:
  -
    Title: Variables and Memory
    Description: "Variable Scope, Variables Are References, Problem Set: Variables and Memory"
    UID: 8add2047-cbf3-4f35-9707-7c75bf919918
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 7bac503f-1fd7-4979-9d74-3e17be1fd59e
        Path: /variables-and-memory/variable-scope.md
      -
        Type: Lesson
        UID: b995d045-d2e8-4c44-9179-ea82c25a3376
        Path: /variables-and-memory/variables-are-references.md
      -
        Type: Lesson
        UID: 43d36cab-991c-47a7-bdb2-86b6d77d4af3
        Path: /variables-and-memory/problem-set-variables-and-memory.md
      
  -
    Title: Big O
    Description: "Time and Space Complexity, Big O Notation, Big O Analysis, Problem Set: Big O"
    UID: f2703dfead197309bf41c0a2d8ff1daf
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 81281faf1d71e4872fb5ca286cc3618e
        Path: /big-o/big-o.instructor.md
      -
        Type: Lesson
        UID: b0ad60b6fe7116d3b63fdb9b4cc4bfde
        Path: /big-o/time-and-space-complexity.md
      -
        Type: Lesson
        UID: 97a53b0bc90b67970a5b0f0c61472464
        Path: /big-o/big-o-notation.md
      -
        Type: Lesson
        UID: 46f8d000785c9cd1b0112854c419f232
        Path: /big-o/big-o-analysis.md
      -
        Type: Lesson
        UID: 2f278585-be40-45c6-ba3e-330f06fc098e
        Path: /big-o/binary-search.md
      -
        Type: Lesson
        UID: 90465d8c4c1af56aed98039f4e95687c
        Path: /big-o/problem-set-big-o.md
  -
    Title: Lists and Memory
    Description: "Lists and Memory, Lists as References, Lists and Big O, Problem Set: Lists and Memory"
    UID: fc8d96af-1277-4efc-8e4c-a7bb2facddb9
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 0180eb42-ed8d-4f51-bcc2-2fe1e2f575c8
        Path: /lists-and-memory/lists-and-memory.md
      -
        Type: Lesson
        UID: f7fda59b-c157-49bb-aaf9-fe305904d0b7
        Path: /lists-and-memory/lists-as-references.md
      -
        Type: Lesson
        UID: 5395b235-30dc-47a8-a077-ac5cf578971c
        Path: /lists-and-memory/lists-and-big-o.md
      -
        Type: Lesson
        UID: a30aecf4-6f22-4d9c-87b6-6dbdd4e68686
        Path: /lists-and-memory/sorting-algorithms-lists-memory.md
      -
        Type: Lesson
        UID: 6703f700-3d4c-42bb-b0c0-35a3ea9c6c67
        Path: /sorting-algorithms/insertion-sort.md
      -
        Type: Lesson
        UID: 36a61d83-b47f-414f-a6f0-3bd4331e713f
        Path: /lists-and-memory/problem-set-lists-and-memory.md
      -
        Type: Lesson
        UID: 383253988f7afc58dd4fe867d42d7cad
        Path: /sorting-algorithms/problem-set-sorting-algorithms.md
  -
    Title: Hash Tables
    Description: "Overview of Hash Tables, Using Hash Tables, Problem Set: Hash Tables"
    UID: fac6e79e15b06e536f52e19c118bfff2
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 6eb75125c1055fad73ea77b1decf3b9b
        Path: /hash-tables/hash-tables.instructor.md
      -
        Type: Lesson
        UID: 98bd2c57dd4d374c50f82260abf950bc
        Path: /hash-tables/overview-of-hash-tables.md
      -
        Type: Lesson
        UID: 423176ceb4ba129653c93c83452643f4
        Path: /hash-tables/using-hash-tables.md
      -
        Type: Lesson
        UID: 912e7b7efb8219dbd6639bdb575322bb
        Path: /hash-tables/problem-set-hash-tables.md
  -
    Title: Sorting Algorithms
    Description: "Sorting Algorithms, Bubble Sort, Selection Sort, Insertion Sort, Merge Sort, Problem Set: Sorting Algorithms"
    UID: 184d8af4792d6c2f80c90b27919caa10
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 11ed7c3b-0b29-400d-9ed4-4af6ab4ba72d
        Path: /sorting-algorithms/sorting-algorithms.instructor.md
      -
        Type: Lesson
        UID: 32b0bd4445f66fd2663288c634432c2e
        Path: /sorting-algorithms/sorting-algorithms.md
      -
        Type: Lesson
        UID: 64b3cc9b8ee0c4d4d7d0dadbaa0d618d
        Path: /sorting-algorithms/merge-sort.md
      -
        Type: Instructor
        UID: 70acaebba6da64c98fef0d184cd40e5b
        Path: /sorting-algorithms/activity-sorting-algorithms.instructor.md
      -
        Type: Resource
        UID: 0806cdb2d0a4b885790d3793999db841
        Path: /sorting-algorithms/bubble-sort.md
      -
        Type: Resource
        UID: 1dc3ffdcda584ccb3a445105b67bf21f
        Path: /sorting-algorithms/selection-sort.md
  -
    Title: Recursion
    Description: "Intro to Recursion, Reading Recursive Code, Writing Recursive Code, Problem Set: Recursion Pt. 1, Problem Set: Recursion Pt. 2"
    UID: 12fa464a36f8e5a187f5acfde99b7029
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 9314cec297d08f8e6944d4ffa8d8ebf7
        Path: /recursion/recursion.instructor.md
      -
        Type: Lesson
        UID: 741b7dd7a6160942b5f7fc2dff011f50
        Path: /recursion/intro-to-recursion.md
      -
        Type: Lesson
        UID: 4464e923942b9d0395ac38e687fbaeb3
        Path: /recursion/reading-recursive-code.md
      -
        Type: Lesson
        UID: 21bc10ab78c0a1e7822b8021150feebd
        Path: /recursion/writing-recursive-code.md
      -
        Type: Lesson
        UID: be58d3489bf4314f9ddf9703624e2842
        Path: /recursion/problem-set-recursion-pt-1.md
      -
        Type: Lesson
        UID: 4dc6f963f2f2d529d9b3dfe7b6dbc19f
        Path: /recursion/problem-set-recursion-pt-2.md
      -
        Type: Checkpoint
        UID: 96d170c9
        Path: /recursion/problem-set-submit.checkpoint.md
  -
    Title: "Algorithmic Strategies"
    Description: "Divide and Conquer, Dynamic Programming, Problem Set: Algorithmic Strategies"
    UID: 7379a433-3626-43b2-840b-ae98bd890555
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 282c6bfa
        Path: /algorithmic-strategies/algorithmic-strategies.instructor.md
      -
        Type: Lesson
        UID: 31eb5440
        Path: /algorithmic-strategies/divide-and-conquer.md
      -
        Type: Lesson
        UID: a9083082
        Path: /algorithmic-strategies/dynamic-programming.md
      -
        Type: Lesson
        UID: 673f70af
        Path: /algorithmic-strategies/problem-set-algorithmic-strategies.md